name: Launch EC2 with Key Pair

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: "EC2 instance name"
        required: true
        default: "gh-instance"

env:
  AWS_REGION: "eu-west-1"

permissions:
  id-token: write
  contents: read

jobs:
  create-and-launch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::411640679017:role/GitHubActionsRole2
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Create EC2 key pair
        id: create_key
        run: |
          aws ec2 create-key-pair \
            --key-name "${{ github.event.inputs.instance_name }}-key" \
            --key-type rsa \
            --key-format pem \
            --query 'KeyMaterial' \
            --output text > key.pem

          chmod 400 key.pem
          
      - name: Upload Key Pair as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ec2-key
          path: key.pem
          
      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
          --image-id ami-0df368112825f8d8f \
          --instance-type t2.micro \
          --key-name "gh-instance-key" \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${{ github.event.inputs.instance_name }} }]" \
          --region $AWS_REGION

