name: Reusable Workflow
on:
  push:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
        default: "Ibrahim"
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.username }} from test_dispatch branch"
